const Routes = {
    home: '/',
    logIn: '/login',
    register: '/sign-up',
    getOTPRegister: '/accuracy-OTP',
    getOTPLogIn: '/accuracy-OTP-email',
    forgotPass: '/forgot-password',
    shop: '/products',
    cart: '/cart',
    checkOut: '/check-out',
    detailProduct: '/product-detail',
    detailProductID: '/product-detail/:id',
    profileHomeProfile: '/profile',
    profileFavouriteProfile: '/favorites-profile',
    profileAddressProfile: '/address-profile',
    profileHistoryPaymentProfile: '/order-history-profile',
    profileAccountProfile: '/settings-profile',
    profilePassWordProfile: '/passwords-profile',
    detailOrder: '/order-detail',
    detailOrderID: '/order-detail/:id',
    tableSize: '/size-table',
    policy: '/policy',
    error: '*',
};

export default Routes;
